# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e41b15eb1c956cf57bda6d27d75d11d685b7b53cba3b4f6769ba99b95d5dd4887a10e9dc69a165ccb6548a851f43b34e737b0995a6dd97ca13d71a3a8d05a91b

test:
  secret_key_base: 88227260bb85418cc04b3edd9112a4c4dea94c0ed976d0f685e23539a1da8fd7409809c409861559e49d063008fa802957c53ccb215e604f035d554b860b683e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
